from nicegui import ui


class ControlPanel:
    def __init__(self):
        self.create_control_panel()

    def create_control_panel(self): ...

    def create_items_panel(self): ...

    def create_boxes_panel(self): ...

    def create_algorithm_panel(self): ...

    def create_packing_button(self): ...

    def create_logs_view(self): ...

    def add_item(self): ...

    def delete_item(self, item_id: int): ...
